-- Lua World Initialization Script
-- This runs automatically when the Lua Scripting World loads.

print("=== Cinnamon Lua Scripting Engine ===")
print("Welcome to the Lua World!")
print("Press Enter or T to open the Lua console.")
print("")
print("Available namespaces:")
print("  world     - Time, gravity, entity queries")
print("  entity    - Spawn entities, spawners, trigger areas")
print("  terrain   - Place, remove, fill terrain blocks")
print("  particles - Spawn particle effects")
print("  lights    - Add and configure dynamic lights")
print("  sound     - Play sounds and music")
print("  events    - Register event callbacks")
print("  commands  - Register custom commands")
print("  registry  - Browse available types")
print("  hud       - Custom HUD text and progress bars")
print("  camera    - Camera position and mode")
print("  player    - Player state and abilities")
print("")
print("Example: runScript('examples/demo.lua')")
print("Type help() for a quick reference.")
print("")

-- Help function
function help()
    print("=== Quick Reference ===")
    print("")
    print("-- Terrain --")
    print("terrain.place('BOX', 0, 1, 0, 'GRASS')")
    print("terrain.fill(-5, 0, -5, 5, 0, 5, 'COBBLESTONE')")
    print("terrain.remove(0, 1, 0)")
    print("terrain.mengerSponge(2, 0, 1, 0, 'GOLD')")
    print("")
    print("-- Entities --")
    print("entity.spawn('DUMMY', 0, 1, 0)")
    print("entity.spawn('CART', 3, 1, 0)")
    print("entity.spawnSpawner('DUMMY', 0, 3, 0, 8, 100)")
    print("")
    print("-- Lights --")
    print("lights.addPoint({x=0, y=5, z=0, color=0xFF0000, intensity=2.0})")
    print("lights.addSpot({x=0, y=8, z=0, dx=0, dy=-1, dz=0, angle=30})")
    print("")
    print("-- Particles --")
    print("particles.spawn('CONFETTI', 0, 3, 0)")
    print("particles.spawn('FIRE', 0, 1, 0, {count=10})")
    print("particles.spawnText('Hello!', 0, 3, 0, 60)")
    print("")
    print("-- Sound --")
    print("sound.play('sounds/click.ogg', 'GUI')")
    print("")
    print("-- Events --")
    print("events.after(20, function() print('delayed!') end)")
    print("events.every(40, function() print('repeating!') end)")
    print("")
    print("-- Player --")
    print("player.setPos(0, 5, 0)")
    print("player.setGodMode(true)")
    print("player.setCanFly(true)")
    print("")
    print("-- HUD --")
    print("hud.setText('msg', 100, 50, 'Hello World!', 0xFFFFFF)")
    print("hud.setProgressBar('hp', 100, 70, 200, 10, 0.75, 0xFF00FF00)")
    print("")
    print("-- Scripts --")
    print("runScript('examples/demo.lua')")
    print("runScript('examples/terrain_art.lua')")
    print("runScript('examples/disco_lights.lua')")
    print("runScript('examples/particle_show.lua')")
end

-- Place a welcome sign using terrain
terrain.place("BOX", 0, 1, 0, "GOLD")
terrain.place("BOX", 0, 2, 0, "GOLD")
terrain.place("BOX", 0, 3, 0, "GOLD")

-- Add a warm welcome light
lights.addPoint({x=0, y=5, z=0, color=0xFFAA44, intensity=1.5})

print("World loaded! Try typing: help()")

runScript("examples/terrain_art.lua")