package cinnamon.events;

public enum EventType {
    CLIENT_INIT,
    CLIENT_EXIT,

    TICK_BEFORE_WORLD,
    TICK_BEFORE_GUI,
    TICK_END,

    RENDER_BEFORE_WORLD,
    RENDER_BEFORE_GUI,
    RENDER_END,

    RESOURCE_INIT,
    RESOURCE_FREE,

    WINDOW_MOVE,
    WINDOW_RESIZE,
    WINDOW_FOCUSED,
    FILES_DROPPED,

    KEY_PRESS,
    CHAR_TYPED,

    MOUSE_PRESS,
    MOUSE_MOVE,
    MOUSE_SCROLL,

    XR_BUTTON_PRESS,
    XR_TRIGGER_PRESS,
    XR_JOYSTICK_MOVE,

    JOYSTICK_BUTTON_PRESS,
    JOYSTICK_AXIS_MOVE,
    JOYSTICK_HAT_MOVE,
    GAMEPAD_BUTTON_PRESS,
    GAMEPAD_AXIS_MOVE,
}
