package cinnamon.events;

public enum EventType {
    CLIENT_INIT,

    TICK_BEFORE_WORLD,
    TICK_BEFORE_GUI,
    TICK_END,

    RENDER_BEFORE_WORLD,
    RENDER_BEFORE_GUI,
    RENDER_END,

    RESOURCE_INIT,
    RESOURCE_FREE,

    KEY_PRESS,
    CHAR_TYPED,
    MOUSE_PRESS,
    MOUSE_MOVE,
    SCROLL,
    WINDOW_MOVE,
    WINDOW_RESIZE,
    WINDOW_FOCUSED,
    FILES_DROPPED,

    XR_BUTTON_PRESS,
    XR_TRIGGER_PRESS,
    XR_JOYSTICK_MOVE
}
